//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.15 at 02:39:02 PM WAT 
//


package com.stanbic.staffCompanion.CustomerOnboarding.AccountOpening.DTOs.redboxInterface.requestManager;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.stanbic.salesforce.service.CAPSIntegration.utils.redboxClient.requestManager.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Request_QNAME = new QName("http://soap.request.manager.redbox.stanbic.com/", "request");
    private final static QName _Response_QNAME = new QName("http://soap.request.manager.redbox.stanbic.com/", "response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.stanbic.salesforce.service.CAPSIntegration.utils.redboxClient.requestManager.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestManagerRequest }
     * 
     */
    public RequestManagerRequest createRequestManagerRequest() {
        return new RequestManagerRequest();
    }

    /**
     * Create an instance of {@link RequestManagerResponse }
     * 
     */
    public RequestManagerResponse createRequestManagerResponse() {
        return new RequestManagerResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestManagerRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestManagerRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.request.manager.redbox.stanbic.com/", name = "request")
    public JAXBElement<RequestManagerRequest> createRequest(RequestManagerRequest value) {
        return new JAXBElement<RequestManagerRequest>(_Request_QNAME, RequestManagerRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestManagerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestManagerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.request.manager.redbox.stanbic.com/", name = "response")
    public JAXBElement<RequestManagerResponse> createResponse(RequestManagerResponse value) {
        return new JAXBElement<RequestManagerResponse>(_Response_QNAME, RequestManagerResponse.class, null, value);
    }

}
